services:
  api:
    build:
      context: .
      dockerfile: UnivCtaCte.Api/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ConnectionStrings__dbCtaCte=Host=${POSTGRES_IP_SERVER};Port=5432;Database=${POSTGRES_BD_NAME};Username=postgres;Password=${POSTGRES_ROOT_PASSWORD};